version: '3.8'

services:
  timescaledb:
    build:
        context: .
        dockerfile: Dockerfile
        target: timescale_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: postgres
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "8001:5432"
